minio:
  endpoint: ""
  access_key: ""
  secret_key: ""
  region: "us-east-1"
  secure: false
  frames_bucket: ""
  gradcam_frames_bucket: ""

laravel:
  base_url: ""
  inference_endpoint: "/api/inference/{video_id}"

model:
  name: "swin_base_patch4_window7_224"
  # download from release page
  weights_remote_path: "https://github.com/recluzegeek/deepscan-api/releases/download/v0.1/swin_model.pth"
  weights_download_path: ""
  num_classes: 2

paths:
  frames_path: "../temp-frames/"
