api:
  host: "0.0.0.0"
  port: 8001

laravel:
  base_url: "http://localhost:8000"
  inference_endpoint: "/api/inference/{video_id}"

model:
  name: "swin_base_patch4_window7_224"
  # download from release page
  weights_remote_path: "https://github.com/recluzegeek/deepscan-api/releases/download/v0.1/swin_model.pth"
  weights_download_path: ""
  num_classes: 2

paths:
  frames_base_path: "/home/recluzegeek/deepscan-web/storage/app/frames"
