api:
  host: "0.0.0.0"
  port: 8001

laravel:
  base_url: "http://127.0.0.1:8000"
  inference_endpoint: "/inference/{video_id}"

model:
  name: "tf_efficientnet_b7_ns"
  weights_path: "/mnt/win/model-weights/efficient-net/4_epochs.pth"
  num_classes: 2

paths:
  frames_base_path: "/mnt/win/deepscan-web/storage/app/frames"
