minio:
  endpoint:
  access_key:
  secret_key:
  secure: false

laravel:
  base_url:
  inference_endpoint: "/api/inference/{video_id}"

model:
  name: "swin_base_patch4_window7_224"
  # download from release page
  weights_remote_path: "https://github.com/recluzegeek/deepscan-api/releases/download/v0.1/swin_model.pth"
  weights_download_path: ""
  num_classes: 2

paths:
  frames_base_path:
